spring.application.name=farm-direct

# Database Configuration
spring.datasource.url=jdbc:mysql://shortline.proxy.rlwy.net:16932/railway?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=lVkXhbNERMjTWVQJsxmpLzNnWjueUbon
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Web
server.port=${PORT:8080}
